group_imports = "StdExternalCrate"
imports_indent = "Block"
imports_layout = "Mixed"
imports_granularity = "Crate"
merge_imports = true
max_width = 120
use_small_heuristics = "Max"
format_strings = true
format_code_in_doc_comments = true
use_field_init_shorthand = true
newline_style = "Unix"
unstable_features = true
wrap_comments = true
comment_width = 140
normalize_comments = true
