[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

[registries.crates.io]
protocol = "sparse"

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Zshare-generics=n", "-Zthreads=16"]
